export const paises = [
  { codigo: 'AF', nombre: 'Afganistán' },
  { codigo: 'AL', nombre: 'Albania' },
  { codigo: 'DE', nombre: 'Alemania' },
  { codigo: 'AD', nombre: 'Andorra' },
  { codigo: 'AO', nombre: 'Angola' },
  { codigo: 'AI', nombre: 'Anguila' },
  { codigo: 'AQ', nombre: 'Antártida' },
  { codigo: 'AG', nombre: 'Antigua y Barbuda' },
  { codigo: 'SA', nombre: 'Arabia Saudí' },
  { codigo: 'DZ', nombre: 'Argelia' },
  { codigo: 'AR', nombre: 'Argentina' },
  { codigo: 'AM', nombre: 'Armenia' },
  { codigo: 'AW', nombre: 'Aruba' },
  { codigo: 'AU', nombre: 'Australia' },
  { codigo: 'AT', nombre: 'Austria' },
  { codigo: 'AZ', nombre: 'Azerbaiyán' },
  { codigo: 'BS', nombre: 'Bahamas' },
  { codigo: 'BD', nombre: 'Bangladés' },
  { codigo: 'BB', nombre: 'Barbados' },
  { codigo: 'BH', nombre: 'Baréin' },
  { codigo: 'BE', nombre: 'Bélgica' },
  { codigo: 'BZ', nombre: 'Belice' },
  { codigo: 'BJ', nombre: 'Benín' },
  { codigo: 'BM', nombre: 'Bermudas' },
  { codigo: 'BY', nombre: 'Bielorrusia' },
  { codigo: 'BO', nombre: 'Bolivia' },
  { codigo: 'BA', nombre: 'Bosnia y Herzegovina' },
  { codigo: 'BW', nombre: 'Botsuana' },
  { codigo: 'BR', nombre: 'Brasil' },
  { codigo: 'BN', nombre: 'Brunéi' },
  { codigo: 'BG', nombre: 'Bulgaria' },
  { codigo: 'BF', nombre: 'Burkina Faso' },
  { codigo: 'BI', nombre: 'Burundi' },
  { codigo: 'BT', nombre: 'Bután' },
  { codigo: 'CV', nombre: 'Cabo Verde' },
  { codigo: 'KH', nombre: 'Camboya' },
  { codigo: 'CM', nombre: 'Camerún' },
  { codigo: 'CA', nombre: 'Canadá' },
  { codigo: 'IC', nombre: 'Canarias' },
  { codigo: 'BQ', nombre: 'Caribe neerlandés' },
  { codigo: 'QA', nombre: 'Catar' },
  { codigo: 'EA', nombre: 'Ceuta y Melilla' },
  { codigo: 'TD', nombre: 'Chad' },
  { codigo: 'CZ', nombre: 'Chequia' },
  { codigo: 'CL', nombre: 'Chile' },
  { codigo: 'CN', nombre: 'China' },
  { codigo: 'CY', nombre: 'Chipre' },
  { codigo: 'VA', nombre: 'Ciudad del Vaticano' },
  { codigo: 'CO', nombre: 'Colombia' },
  { codigo: 'KM', nombre: 'Comoras' },
  { codigo: 'CG', nombre: 'Congo' },
  { codigo: 'KP', nombre: 'Corea del Norte' },
  { codigo: 'KR', nombre: 'Corea del Sur' },
  { codigo: 'CR', nombre: 'Costa Rica' },
  { codigo: 'CI', nombre: 'Côte d’Ivoire' },
  { codigo: 'HR', nombre: 'Croacia' },
  { codigo: 'CU', nombre: 'Cuba' },
  { codigo: 'CW', nombre: 'Curazao' },
  { codigo: 'DG', nombre: 'Diego García' },
  { codigo: 'DK', nombre: 'Dinamarca' },
  { codigo: 'DM', nombre: 'Dominica' },
  { codigo: 'EC', nombre: 'Ecuador' },
  { codigo: 'EG', nombre: 'Egipto' },
  { codigo: 'SV', nombre: 'El Salvador' },
  { codigo: 'AE', nombre: 'Emiratos Árabes Unidos' },
  { codigo: 'ER', nombre: 'Eritrea' },
  { codigo: 'SK', nombre: 'Eslovaquia' },
  { codigo: 'SI', nombre: 'Eslovenia' },
  { codigo: 'ES', nombre: 'España' },
  { codigo: 'US', nombre: 'Estados Unidos' },
  { codigo: 'EE', nombre: 'Estonia' },
  { codigo: 'SZ', nombre: 'Esuatini' },
  { codigo: 'ET', nombre: 'Etiopía' },
  { codigo: 'PH', nombre: 'Filipinas' },
  { codigo: 'FI', nombre: 'Finlandia' },
  { codigo: 'FJ', nombre: 'Fiyi' },
  { codigo: 'FR', nombre: 'Francia' },
  { codigo: 'GA', nombre: 'Gabón' },
  { codigo: 'GM', nombre: 'Gambia' },
  { codigo: 'GE', nombre: 'Georgia' },
  { codigo: 'GH', nombre: 'Ghana' },
  { codigo: 'GI', nombre: 'Gibraltar' },
  { codigo: 'GD', nombre: 'Granada' },
  { codigo: 'GR', nombre: 'Grecia' },
  { codigo: 'GL', nombre: 'Groenlandia' },
  { codigo: 'GP', nombre: 'Guadalupe' },
  { codigo: 'GU', nombre: 'Guam' },
  { codigo: 'GT', nombre: 'Guatemala' },
  { codigo: 'GF', nombre: 'Guayana Francesa' },
  { codigo: 'GG', nombre: 'Guernsey' },
  { codigo: 'GN', nombre: 'Guinea' },
  { codigo: 'GQ', nombre: 'Guinea Ecuatorial' },
  { codigo: 'GW', nombre: 'Guinea-Bisáu' },
  { codigo: 'GY', nombre: 'Guyana' },
  { codigo: 'HT', nombre: 'Haití' },
  { codigo: 'HN', nombre: 'Honduras' },
  { codigo: 'HU', nombre: 'Hungría' },
  { codigo: 'IN', nombre: 'India' },
  { codigo: 'ID', nombre: 'Indonesia' },
  { codigo: 'IQ', nombre: 'Irak' },
  { codigo: 'IR', nombre: 'Irán' },
  { codigo: 'IE', nombre: 'Irlanda' },
  { codigo: 'AC', nombre: 'Isla de la Ascensión' },
  { codigo: 'IM', nombre: 'Isla de Man' },
  { codigo: 'CX', nombre: 'Isla de Navidad' },
  { codigo: 'NF', nombre: 'Isla Norfolk' },
  { codigo: 'IS', nombre: 'Islandia' },
  { codigo: 'AX', nombre: 'Islas Åland' },
  { codigo: 'KY', nombre: 'Islas Caimán' },
  { codigo: 'CC', nombre: 'Islas Cocos' },
  { codigo: 'CK', nombre: 'Islas Cook' },
  { codigo: 'FO', nombre: 'Islas Feroe' },
  { codigo: 'GS', nombre: 'Islas Georgia del Sur y Sandwich del Sur' },
  { codigo: 'FK', nombre: 'Islas Malvinas' },
  { codigo: 'MP', nombre: 'Islas Marianas del Norte' },
  { codigo: 'MH', nombre: 'Islas Marshall' },
  { codigo: 'UM', nombre: 'Islas menores alejadas de EE. UU.' },
  { codigo: 'PN', nombre: 'Islas Pitcairn' },
  { codigo: 'SB', nombre: 'Islas Salomón' },
  { codigo: 'TC', nombre: 'Islas Turcas y Caicos' },
  { codigo: 'VG', nombre: 'Islas Vírgenes Británicas' },
  { codigo: 'VI', nombre: 'Islas Vírgenes de EE. UU.' },
  { codigo: 'IL', nombre: 'Israel' },
  { codigo: 'IT', nombre: 'Italia' },
  { codigo: 'JM', nombre: 'Jamaica' },
  { codigo: 'JP', nombre: 'Japón' },
  { codigo: 'JE', nombre: 'Jersey' },
  { codigo: 'JO', nombre: 'Jordania' },
  { codigo: 'KZ', nombre: 'Kazajistán' },
  { codigo: 'KE', nombre: 'Kenia' },
  { codigo: 'KG', nombre: 'Kirguistán' },
  { codigo: 'KI', nombre: 'Kiribati' },
  { codigo: 'XK', nombre: 'Kosovo' },
  { codigo: 'KW', nombre: 'Kuwait' },
  { codigo: 'LA', nombre: 'Laos' },
  { codigo: 'LS', nombre: 'Lesoto' },
  { codigo: 'LV', nombre: 'Letonia' },
  { codigo: 'LB', nombre: 'Líbano' },
  { codigo: 'LR', nombre: 'Liberia' },
  { codigo: 'LY', nombre: 'Libia' },
  { codigo: 'LI', nombre: 'Liechtenstein' },
  { codigo: 'LT', nombre: 'Lituania' },
  { codigo: 'LU', nombre: 'Luxemburgo' },
  { codigo: 'MK', nombre: 'Macedonia' },
  { codigo: 'MG', nombre: 'Madagascar' },
  { codigo: 'MY', nombre: 'Malasia' },
  { codigo: 'MW', nombre: 'Malaui' },
  { codigo: 'MV', nombre: 'Maldivas' },
  { codigo: 'ML', nombre: 'Mali' },
  { codigo: 'MT', nombre: 'Malta' },
  { codigo: 'MA', nombre: 'Marruecos' },
  { codigo: 'MQ', nombre: 'Martinica' },
  { codigo: 'MU', nombre: 'Mauricio' },
  { codigo: 'MR', nombre: 'Mauritania' },
  { codigo: 'YT', nombre: 'Mayotte' },
  { codigo: 'MX', nombre: 'México' },
  { codigo: 'FM', nombre: 'Micronesia' },
  { codigo: 'MD', nombre: 'Moldavia' },
  { codigo: 'MC', nombre: 'Mónaco' },
  { codigo: 'MN', nombre: 'Mongolia' },
  { codigo: 'ME', nombre: 'Montenegro' },
  { codigo: 'MS', nombre: 'Montserrat' },
  { codigo: 'MZ', nombre: 'Mozambique' },
  { codigo: 'MM', nombre: 'Myanmar (Birmania)' },
  { codigo: 'NA', nombre: 'Namibia' },
  { codigo: 'NR', nombre: 'Nauru' },
  { codigo: 'NP', nombre: 'Nepal' },
  { codigo: 'NI', nombre: 'Nicaragua' },
  { codigo: 'NE', nombre: 'Níger' },
  { codigo: 'NG', nombre: 'Nigeria' },
  { codigo: 'NU', nombre: 'Niue' },
  { codigo: 'NO', nombre: 'Noruega' },
  { codigo: 'NC', nombre: 'Nueva Caledonia' },
  { codigo: 'NZ', nombre: 'Nueva Zelanda' },
  { codigo: 'OM', nombre: 'Omán' },
  { codigo: 'NL', nombre: 'Países Bajos' },
  { codigo: 'PK', nombre: 'Pakistán' },
  { codigo: 'PW', nombre: 'Palaos' },
  { codigo: 'PA', nombre: 'Panamá' },
  { codigo: 'PG', nombre: 'Papúa Nueva Guinea' },
  { codigo: 'PY', nombre: 'Paraguay' },
  { codigo: 'PE', nombre: 'Perú' },
  { codigo: 'PF', nombre: 'Polinesia Francesa' },
  { codigo: 'PL', nombre: 'Polonia' },
  { codigo: 'PT', nombre: 'Portugal' },
  { codigo: 'XA', nombre: 'Pseudo-Accents' },
  { codigo: 'XB', nombre: 'Pseudo-Bidi' },
  { codigo: 'PR', nombre: 'Puerto Rico' },
  { codigo: 'HK', nombre: 'RAE de Hong Kong (China)' },
  { codigo: 'MO', nombre: 'RAE de Macao (China)' },
  { codigo: 'GB', nombre: 'Reino Unido' },
  { codigo: 'CF', nombre: 'República Centroafricana' },
  { codigo: 'CD', nombre: 'República Democrática del Congo' },
  { codigo: 'DO', nombre: 'República Dominicana' },
  { codigo: 'RE', nombre: 'Reunión' },
  { codigo: 'RW', nombre: 'Ruanda' },
  { codigo: 'RO', nombre: 'Rumanía' },
  { codigo: 'RU', nombre: 'Rusia' },
  { codigo: 'EH', nombre: 'Sáhara Occidental' },
  { codigo: 'WS', nombre: 'Samoa' },
  { codigo: 'AS', nombre: 'Samoa Americana' },
  { codigo: 'BL', nombre: 'San Bartolomé' },
  { codigo: 'KN', nombre: 'San Cristóbal y Nieves' },
  { codigo: 'SM', nombre: 'San Marino' },
  { codigo: 'MF', nombre: 'San Martín' },
  { codigo: 'PM', nombre: 'San Pedro y Miquelón' },
  { codigo: 'VC', nombre: 'San Vicente y las Granadinas' },
  { codigo: 'SH', nombre: 'Santa Elena' },
  { codigo: 'LC', nombre: 'Santa Lucía' },
  { codigo: 'ST', nombre: 'Santo Tomé y Príncipe' },
  { codigo: 'SN', nombre: 'Senegal' },
  { codigo: 'RS', nombre: 'Serbia' },
  { codigo: 'SC', nombre: 'Seychelles' },
  { codigo: 'SL', nombre: 'Sierra Leona' },
  { codigo: 'SG', nombre: 'Singapur' },
  { codigo: 'SX', nombre: 'Sint Maarten' },
  { codigo: 'SY', nombre: 'Siria' },
  { codigo: 'SO', nombre: 'Somalia' },
  { codigo: 'LK', nombre: 'Sri Lanka' },
  { codigo: 'ZA', nombre: 'Sudáfrica' },
  { codigo: 'SD', nombre: 'Sudán' },
  { codigo: 'SS', nombre: 'Sudán del Sur' },
  { codigo: 'SE', nombre: 'Suecia' },
  { codigo: 'CH', nombre: 'Suiza' },
  { codigo: 'SR', nombre: 'Surinam' },
  { codigo: 'SJ', nombre: 'Svalbard y Jan Mayen' },
  { codigo: 'TH', nombre: 'Tailandia' },
  { codigo: 'TW', nombre: 'Taiwán' },
  { codigo: 'TZ', nombre: 'Tanzania' },
  { codigo: 'TJ', nombre: 'Tayikistán' },
  { codigo: 'IO', nombre: 'Territorio Británico del Océano Índico' },
  { codigo: 'TF', nombre: 'Territorios Australes Franceses' },
  { codigo: 'PS', nombre: 'Territorios Palestinos' },
  { codigo: 'TL', nombre: 'Timor-Leste' },
  { codigo: 'TG', nombre: 'Togo' },
  { codigo: 'TK', nombre: 'Tokelau' },
  { codigo: 'TO', nombre: 'Tonga' },
  { codigo: 'TT', nombre: 'Trinidad y Tobago' },
  { codigo: 'TA', nombre: 'Tristán de Acuña' },
  { codigo: 'TN', nombre: 'Túnez' },
  { codigo: 'TM', nombre: 'Turkmenistán' },
  { codigo: 'TR', nombre: 'Turquía' },
  { codigo: 'TV', nombre: 'Tuvalu' },
  { codigo: 'UA', nombre: 'Ucrania' },
  { codigo: 'UG', nombre: 'Uganda' },
  { codigo: 'UY', nombre: 'Uruguay' },
  { codigo: 'UZ', nombre: 'Uzbekistán' },
  { codigo: 'VU', nombre: 'Vanuatu' },
  { codigo: 'VE', nombre: 'Venezuela' },
  { codigo: 'VN', nombre: 'Vietnam' },
  { codigo: 'WF', nombre: 'Wallis y Futuna' },
  { codigo: 'YE', nombre: 'Yemen' },
  { codigo: 'DJ', nombre: 'Yibuti' },
  { codigo: 'ZM', nombre: 'Zambia' },
  { codigo: 'ZW', nombre: 'Zimbabue' }
];
